name = "All Mods"
author = "Nadwey"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7fa96fb9fc0163394913664226df45eb8814d9447f2312784731b061be3e4c50"

[versions]
forge = "47.3.12"
minecraft = "1.20.1"
