name = "All Mods"
author = "Nadwey"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "da7afadbc19b18cd944a8fca6ba99748e55813b05da73f9bade3bc4b0f96d2c3"

[versions]
forge = "47.3.12"
minecraft = "1.20.1"
